export const LOCAL_CH_POPULAR_CATEGORIES = [
  "Ristorante",
  "Parrucchiere",
  "Medico",
  "Podologo",
  "Dermatologo",
  "Dentista",
  "Psichiatra",
  "Fisioterapia",
  "Ginecologo",
  "Osteopata",
  "Taxi",
  "Estetista",
  "Hotel",
  "Garage",
  "Pulizie",
  "Impresa costruzioni",
  "Oftalmologo",
  "Pedicure",
  "Giardinieri",
  "Fiduciaria",
  "Otorino",
  "Massaggio",
  "Elettricista",
  "Cura delle Unghie",
  "Psicoterapia",
  "Pittore",
  "Impianti sanitari",
  "Trasporti",
  "Psicologia",
  "Avvocato",
  "Architetto",
  "Notaio",
  "Farmacia",
  "Falegnameria",
  "Banca",
  "Assicurazioni",
  "Chiropratici",
  "Campeggio",
  "Pediatra",
  "Studi di Logopedia",
  "Malattie del cuore (Cardiologia)",
  "Veterinario",
  "Rolladen",
  "Lavoro temporaneo e fisso",
  "Pizzeria",
  "Ottico",
  "Carrozzeria",
  "Bed and Breakfast",
  "Traslochi",
  "Immobili",
  "Ergoterapia",
  "Massaggio medico",
  "Studio medico",
  "Scuola guida",
  "Centro medico",
  "Ortopedico",
  "Naturopatia",
  "Agenzia viaggi",
  "Consolato",
  "Fioristi",
  "Impresa di gessatura",
  "Barche e motoscafi, noleggio",
  "Oftalmologia",
  "Macelleria",
  "Ponteggi",
  "Prodotti per cani",
  "Autonoleggio",
  "Idraulico",
  "Psichiatria e psicoterapia infantile e dell'adolescenza",
  "Malattie delle vie urinarie (Urologia)",
  "Immobiliare",
  "Municipio",
  "Pavimenti e rivestimenti in genere",
  "Autoscuole",
  "Kinesiologia",
  "Cucina italiana",
  "Bar",
  "Consulenza per il personale",
  "Agopuntura (escluso dalla rubrica medici)",
  "Endocrinologia-diabetologia",
  "Biciclette",
  "Panetteria e pasticceria",
  "Lattonieri",
  "Massaggio thai",
  "Fotografi",
  "Radiologia diagnostica",
  "Ufficio collocamento",
  "Portineria e servizi immobili",
  "Costruzioni metalliche",
  "Automobili, occasioni",
  "Gastroenterologo",
  "Consulenza fiscale",
  "Elettrodomestici",
  "Ortopedia, articoli e negozi",
  "Take Away",
  "Barbershop",
  "Boutique",
  "Centro",
  "Fitness-Center",
  "Malattie vascolari (Angiologia)",
] as const;
